__author__ = 'dugging'
from tkinter import *


def coal():
    GUICoal = Tk()
    GUICoal.title('Physics Project - Coal')
    GUICoal.geometry('460x700')
    #How It Works
    Label(GUICoal, text='How does it work?', fg='red', font=16).place(x=0, y=0)
    Label(GUICoal, text='Coal is burnt in a boiler and heats water in a vat above it.').place(x=0, y=20)
    Label(GUICoal, text='When the water evaporates, it is compressed.').place(x=0, y=40)
    Label(GUICoal, text='It is then put through a turbine which turns a magnet.').place(x=0, y=60)
    Label(GUICoal, text='This induces an electrical current in the copper cable that surrounds the magnet.').place(x=0, y=80)
    Label(GUICoal, text='The electricity is then distributed by the national grid.').place(x=0, y=100)
    Label(GUICoal, text='--------------------------------------------------------------------------------------', fg='red').place(x=0, y=140)
    #Adv/DisAdv
        #Table
    Label(GUICoal, text='Advantages Vs Disadvantages', fg='red', font=16).place(x=0, y=160)
    Label(GUICoal, text='Advantages', fg='red', font=14).place(x=0, y=200)
    Label(GUICoal, text='Disadvantages', fg='red', font=14).place(x=300, y=200)
    Label(GUICoal, text='--------------------------------------------------------------------------------------', fg='red').place(x=0, y=225)
    Label(GUICoal, text='|---|', fg='red').place(x=200, y=200)
    Label(GUICoal, text='|---|', fg='red').place(x=200, y=225)
    Label(GUICoal, text='|---|', fg='red').place(x=200, y=250)
    Label(GUICoal, text='|---|', fg='red').place(x=200, y=275)
    Label(GUICoal, text='|---|', fg='red').place(x=200, y=300)
    Label(GUICoal, text='|---|', fg='red').place(x=200, y=325)
    Label(GUICoal, text='|---|', fg='red').place(x=200, y=350)
    Label(GUICoal, text='|---|', fg='red').place(x=200, y=375)
    Label(GUICoal, text='|---|', fg='red').place(x=200, y=400)
    Label(GUICoal, text='|---|', fg='red').place(x=200, y=425)
        #Adv
    Label(GUICoal, text='Reliability', font=10).place(x=0, y=245)
    Label(GUICoal, text='-They are reliable for peak times.').place(x=0, y=265)
    Label(GUICoal, text='Affordability', font=10).place(x=0, y=285)
    Label(GUICoal, text='-They are cheap.').place(x=0, y=305)
    Label(GUICoal, text='Abundance', font=10).place(x=0, y=325)
    Label(GUICoal, text='-There are over 300 years of coal left.').place(x=0, y=345)
    Label(GUICoal, text='Known technologies', font=10).place(x=0, y=365)
    Label(GUICoal, text='-We know how it works.').place(x=0, y=385)
    Label(GUICoal, text='Safety', font=10).place(x=0, y=405)
    Label(GUICoal, text='-They are generally safe.').place(x=0, y=425)
        #DisAdv
    Label(GUICoal, text='Greenhouse gas emissions', font=10).place(x=230, y=245)
    Label(GUICoal, text='-They emit Green house gas.').place(x=230, y=265)
    Label(GUICoal, text='Mining destruction', font=10).place(x=230, y=285)
    Label(GUICoal, text='-Mining coal destroys land.').place(x=230, y=305)
    Label(GUICoal, text='Generation  of waste', font=10).place(x=230, y=325)
    Label(GUICoal, text='-They produce tons of unusable waste.').place(x=230, y=345)
    Label(GUICoal, text='Emission of harmful substances', font=10).place(x=230, y=365)
    Label(GUICoal, text='-Substance like mercury\nand sulphur dioxide are released\nwhich cause harm to the\nenvironment people included.').place(x=230, y=385)

    Label(GUICoal, text='Source: http://www.brighthubengineering.com/power-plants/\n115683-advantages-and-disadvantages-of-coal-for-power-plants/').place(x=0, y=450)
    Label(GUICoal, text='--------------------------------------------------------------------------------------', fg='red').place(x=0, y=490)
    #End Adv Vs DiasAdv
    #Case Study
    Label(GUICoal, text='Case Study - Aberthaw', fg='red', font=10).place(x=0, y=510)
    Label(GUICoal, text='Aberthaw is in Barry, Vale of Glamorgan(south wales).').place(x=0, y=530)
    Label(GUICoal, text='It opened in 1966 and has three operational units.').place(x=0, y=530)
    Label(GUICoal, text='It burns 5000-6000 tonnes of coal per day contributing 6-7 GWHrs per year.').place(x=0, y=550)
    Label(GUICoal, text='In response to the renewable energy act in April\n2002 the station uses biofuel as a secondary fuel.').place(x=0, y=570)
    Label(GUICoal, text='In June 2005, station owners npower,agreed to install\nnew Flue Gas Desulfurization(FGD) equipment.').place(x=0, y=600)
    Label(GUICoal, text='The FGD equipment is planned to be installed by 2008,\nreducing sulphur dioxide levels by 90%.').place(x=0, y=635)
    Label(GUICoal, text='Source: http://en.wikipedia.org/wiki/Aberthaw_power_stations').place(x=0, y=670)
    GUICoal.mainloop()


def oil():
    GUIOil = Tk()
    GUIOil.title('Physics Project - Oil')
    GUIOil.geometry('460x690')
    #How It Works
    Label(GUIOil, text='How does it work?', fg='red', font=16).place(x=0, y=0)
    Label(GUIOil, text='Oil is burnt in a boiler and heats water in a vat above it.').place(x=0, y=20)
    Label(GUIOil, text='When the water evaporates, it is compressed.').place(x=0, y=40)
    Label(GUIOil, text='It is then put through a turbine which turns a magnet.').place(x=0, y=60)
    Label(GUIOil, text='This induces an electrical current in the copper cable that surrounds the magnet.').place(x=0, y=80)
    Label(GUIOil, text='The electricity is then distributed by the national grid.').place(x=0, y=100)
    Label(GUIOil, text='--------------------------------------------------------------------------------------', fg='red').place(x=0, y=140)
    #Adv/DisAdv
        #Table
    Label(GUIOil, text='Advantages Vs Disadvantages', fg='red', font=16).place(x=0, y=160)
    Label(GUIOil, text='Advantages', fg='red', font=14).place(x=0, y=200)
    Label(GUIOil, text='Disadvantages', fg='red', font=14).place(x=300, y=200)
    Label(GUIOil, text='--------------------------------------------------------------------------------------', fg='red').place(x=0, y=225)
    Label(GUIOil, text='|---|', fg='red').place(x=200, y=200)
    Label(GUIOil, text='|---|', fg='red').place(x=200, y=225)
    Label(GUIOil, text='|---|', fg='red').place(x=200, y=250)
    Label(GUIOil, text='|---|', fg='red').place(x=200, y=275)
    Label(GUIOil, text='|---|', fg='red').place(x=200, y=300)
    Label(GUIOil, text='|---|', fg='red').place(x=200, y=325)
    Label(GUIOil, text='|---|', fg='red').place(x=200, y=350)
    Label(GUIOil, text='|---|', fg='red').place(x=200, y=375)
    Label(GUIOil, text='|---|', fg='red').place(x=200, y=400)
    Label(GUIOil, text='|---|', fg='red').place(x=200, y=425)
        #Adv
    Label(GUIOil, text='Transportation', font=10).place(x=0, y=245)
    Label(GUIOil, text='-Easily transported by pipes or ship.').place(x=0, y=265)
    Label(GUIOil, text='Potential plots', font=10).place(x=0, y=285)
    Label(GUIOil, text='-Oil plants can be built anywhere\nthere is good transport\nlinks and water supply.').place(x=0, y=305)
    Label(GUIOil, text='Effective', font=10).place(x=0, y=350)
    Label(GUIOil, text='-A large amount of power\ncan be generated per station.').place(x=0, y=370)
        #DisAdv
    Label(GUIOil, text='Greenhouse Emissions', font=10).place(x=230, y=245)
    Label(GUIOil, text='-Greenhouse gasses are emitted.').place(x=230, y=265)
    Label(GUIOil, text='Expensive', font=10).place(x=230, y=285)
    Label(GUIOil, text='-Oil costs more than coal and gas.').place(x=230, y=305)
    Label(GUIOil, text='Non-renewable', font=10).place(x=230, y=325)
    Label(GUIOil, text='-Oil will run out.').place(x=230, y=345)
    Label(GUIOil, text='Emission of harmful substances', font=10).place(x=230, y=365)
    Label(GUIOil, text='-Substance like sulphur dioxide\nare released which cause harm to\nthe environment people included.').place(x=230, y=385)

    Label(GUIOil, text='Source: http://www.eon-uk.com/EnergyExperience/580.htm').place(x=0, y=450)
    Label(GUIOil, text='--------------------------------------------------------------------------------------', fg='red').place(x=0, y=490)
    #End Adv Vs DiasAdv
    #Case Study
    Label(GUIOil, text='Case Study - Bankside', fg='red', font=10).place(x=0, y=510)
    Label(GUIOil, text='The plant is on the south bank of the River Thames in the Bankside district of London.').place(x=0, y=530)
    Label(GUIOil, text='It was commissioned in 1952 and decommissioned in 1981 because of rising oil prices.').place(x=0, y=550)
    Label(GUIOil, text='An application to get the building listed was refused but the BBC\nprogram,"One Foot in the Past", focused on the impendding threat to the biulding.').place(x=0, y=570)
    Label(GUIOil, text='In April 1994, the Tate Gallery announced the the plant would be the home for the\nnew Tate Modern.Construction started in June 1995 and finished in January 2000.').place(x=0, y=610)
    Label(GUIOil, text='Source: http://en.wikipedia.org/wiki/Bankside_Power_Station').place(x=0, y=670)
    GUIOil.mainloop()


def gas():
    GUIGas = Tk()
    GUIGas.title('Physics Project - Gas')
    GUIGas.geometry('460x610')
    #How It Works
    Label(GUIGas, text='How does it work?', fg='red', font=16).place(x=0, y=0)
    Label(GUIGas, text='Gas is burnt in a boiler and heats water in a vat above it.').place(x=0, y=20)
    Label(GUIGas, text='When the water evaporates, it is compressed.').place(x=0, y=40)
    Label(GUIGas, text='It is then put through a turbine which turns a magnet.').place(x=0, y=60)
    Label(GUIGas, text='This induces an electrical current in the copper cable that surrounds the magnet.').place(x=0, y=80)
    Label(GUIGas, text='The electricity is then distributed by the national grid.').place(x=0, y=100)
    Label(GUIGas, text='--------------------------------------------------------------------------------------', fg='red').place(x=0, y=140)
    #Adv/DisAdv
        #Table
    Label(GUIGas, text='Advantages Vs Disadvantages', fg='red', font=16).place(x=0, y=160)
    Label(GUIGas, text='Advantages', fg='red', font=14).place(x=0, y=200)
    Label(GUIGas, text='Disadvantages', fg='red', font=14).place(x=300, y=200)
    Label(GUIGas, text='--------------------------------------------------------------------------------------', fg='red').place(x=0, y=225)
    Label(GUIGas, text='|---|', fg='red').place(x=200, y=200)
    Label(GUIGas, text='|---|', fg='red').place(x=200, y=225)
    Label(GUIGas, text='|---|', fg='red').place(x=200, y=250)
    Label(GUIGas, text='|---|', fg='red').place(x=200, y=275)
    Label(GUIGas, text='|---|', fg='red').place(x=200, y=300)
    Label(GUIGas, text='|---|', fg='red').place(x=200, y=325)
    Label(GUIGas, text='|---|', fg='red').place(x=200, y=350)
    Label(GUIGas, text='|---|', fg='red').place(x=200, y=375)
    Label(GUIGas, text='|---|', fg='red').place(x=200, y=400)
    Label(GUIGas, text='|---|', fg='red').place(x=200, y=425)
        #Adv
    Label(GUIGas, text='Less Harmful', font=10).place(x=0, y=245)
    Label(GUIGas, text='-Less harmful than oil or gas.').place(x=0, y=265)
    Label(GUIGas, text='Storage', font=10).place(x=0, y=285)
    Label(GUIGas, text='-Easily stored and transported.').place(x=0, y=305)
    Label(GUIGas, text='Cleaner', font=10).place(x=0, y=325)
    Label(GUIGas, text='-Gas burns cleaner.').place(x=0, y=345)
    Label(GUIGas, text='Precise', font=10).place(x=0, y=365)
    Label(GUIGas, text='-Can be tuned to be efficient.').place(x=0, y=385)
    Label(GUIGas, text='Abundant', font=10).place(x=0, y=405)
    Label(GUIGas, text='-Reletivly abundant compared\nto other fossil fuels.').place(x=0, y=425)
        #DisAdv
    Label(GUIGas, text='Toxic and Flammable', font=10).place(x=230, y=245)
    Label(GUIGas, text='-Leaks may cause explosions.').place(x=230, y=265)
    Label(GUIGas, text='Greenhouse gasses', font=10).place(x=230, y=285)
    Label(GUIGas, text='-Greenhouse gasses are emitted.').place(x=230, y=305)
    Label(GUIGas, text='Non-renewable', font=10).place(x=230, y=325)
    Label(GUIGas, text='-Will run out.').place(x=230, y=345)

    Label(GUIGas, text='Source: http://www.conserve-energy-future.com/\nadvantages-and-disadvantages-of-natural-gas.php').place(x=0, y=455)
    Label(GUIGas, text='--------------------------------------------------------------------------------------', fg='red').place(x=0, y=490)
    #End Adv Vs DiasAdv
    #Case Study
    Label(GUIGas, text='Case Study - Grain', fg='red', font=10).place(x=0, y=510)
    Label(GUIGas, text='The station is located on the Isle of Grain,Kent.').place(x=0, y=530)
    Label(GUIGas, text='It was commissioned in 1979 and decommissioned in 2012.').place(x=0, y=530)
    Label(GUIGas, text='It had 5 units,2 oil units and 3 gas units.').place(x=0, y=550)
    Label(GUIGas, text='The oil units produced 1.32GW and the gas units produced 1.275GW.').place(x=0, y=570)
    Label(GUIGas, text='Source: http://en.wikipedia.org/wiki/Grain_Power_Station').place(x=0, y=590)
    GUIGas.mainloop()


def biofuel():
    GUIBio = Tk()
    GUIBio.title('Physics Project - Biofuel')
    GUIBio.geometry('460x650')
    #How It Works
    Label(GUIBio, text='How does it work?', fg='red', font=16).place(x=0, y=0)
    Label(GUIBio, text='Biofuel is burnt in a boiler and heats water in a vat above it.').place(x=0, y=20)
    Label(GUIBio, text='When the water evaporates, it is compressed.').place(x=0, y=40)
    Label(GUIBio, text='It is then put through a turbine which turns a magnet.').place(x=0, y=60)
    Label(GUIBio, text='This induces an electrical current in the copper cable that surrounds the magnet.').place(x=0, y=80)
    Label(GUIBio, text='The electricity is then distributed by the national grid.').place(x=0, y=100)
    Label(GUIBio, text='--------------------------------------------------------------------------------------', fg='red').place(x=0, y=140)
    #Adv/DisAdv
        #Table
    Label(GUIBio, text='Advantages Vs Disadvantages', fg='red', font=16).place(x=0, y=160)
    Label(GUIBio, text='Advantages', fg='red', font=14).place(x=0, y=200)
    Label(GUIBio, text='Disadvantages', fg='red', font=14).place(x=300, y=200)
    Label(GUIBio, text='--------------------------------------------------------------------------------------', fg='red').place(x=0, y=225)
    Label(GUIBio, text='|---|', fg='red').place(x=200, y=200)
    Label(GUIBio, text='|---|', fg='red').place(x=200, y=225)
    Label(GUIBio, text='|---|', fg='red').place(x=200, y=250)
    Label(GUIBio, text='|---|', fg='red').place(x=200, y=275)
    Label(GUIBio, text='|---|', fg='red').place(x=200, y=300)
    Label(GUIBio, text='|---|', fg='red').place(x=200, y=325)
    Label(GUIBio, text='|---|', fg='red').place(x=200, y=350)
    Label(GUIBio, text='|---|', fg='red').place(x=200, y=375)
    Label(GUIBio, text='|---|', fg='red').place(x=200, y=400)
    Label(GUIBio, text='|---|', fg='red').place(x=200, y=425)
        #Adv
    Label(GUIBio, text='Cost', font=10).place(x=0, y=245)
    Label(GUIBio, text='-Less expensive fuel than oil/coal.').place(x=0, y=265)
    Label(GUIBio, text='Renewable', font=10).place(x=0, y=285)
    Label(GUIBio, text='-It can be continuously used.').place(x=0, y=305)
    Label(GUIBio, text='Local', font=10).place(x=0, y=325)
    Label(GUIBio, text='-Can be produced locally.').place(x=0, y=345)
    Label(GUIBio, text='Economic', font=10).place(x=0, y=365)
    Label(GUIBio, text='-Local plants creates 1000s of jobs.').place(x=0, y=385)
    Label(GUIBio, text='Less carbon emissions', font=10).place(x=0, y=405)
    Label(GUIBio, text='-Produces less CO2 than coal/oil.').place(x=0, y=425)
        #DisAdv
    Label(GUIBio, text='Energy Density', font=10).place(x=230, y=245)
    Label(GUIBio, text='-It has a lower density than coal/oil.').place(x=230, y=265)
    Label(GUIBio, text='Initial cost', font=10).place(x=230, y=285)
    Label(GUIBio, text='-Biofuel plants/refineries have a high cost.').place(x=230, y=305)
    Label(GUIBio, text='Food prices', font=10).place(x=230, y=325)
    Label(GUIBio, text='-While food is used for fuel other\nfood prices rise.').place(x=230, y=345)

    Label(GUIBio, text='Source: http://greenliving.lovetoknow.com/\nAdvantages_and_Disadvantages_of_Biofuels').place(x=0, y=450)
    Label(GUIBio, text='--------------------------------------------------------------------------------------', fg='red').place(x=0, y=490)
    #End Adv Vs DiasAdv
    #Case Study
    Label(GUIBio, text='Case Study - Glanford', fg='red', font=10).place(x=0, y=510)
    Label(GUIBio, text='The plant is located in Lincolnshire, East Midlands.').place(x=0, y=530)
    Label(GUIBio, text='It was commissioned in 1993.').place(x=0, y=530)
    Label(GUIBio, text='After the BSE crisis in the 1980s millions of cows were killed.').place(x=0, y=550)
    Label(GUIBio, text='Then in May 2000 the station was commissioned to burn them.').place(x=0, y=570)
    Label(GUIBio, text='They have about 2/3 the energy value of coal/oil and is labeled as carbon neutral.').place(x=0, y=590)
    Label(GUIBio, text='Ashes(waste) is about 20% of the fuel by weight.').place(x=0, y=610)
    Label(GUIBio, text='Source: http://en.wikipedia.org/wiki/Glanford_Power_Station').place(x=0, y=630)
    GUIBio.mainloop()


def nuclear():
    GUINuclear = Tk()
    GUINuclear.title('Physics Project - Nuclear(Fission)')
    GUINuclear.geometry('460x650')
    #How It Works
    Label(GUINuclear, text='How does it work?', fg='red', font=16).place(x=0, y=0)
    Label(GUINuclear, text='Nuclear reactions occur in a reactor and heats water in a pipes around it.').place(x=0, y=20)
    Label(GUINuclear, text='The water flows through the pipes to the heat exchanger.').place(x=0, y=40)
    Label(GUINuclear, text='The heat is then transferred from the reactor water to the secondary circuit water.').place(x=0, y=60)
    Label(GUINuclear, text='The secondary water evaporates and is then put through a turbine.').place(x=0, y=80)
    Label(GUINuclear, text='The steam is then cooled,using a third water circuit,and returned to the heat exchange.').place(x=0, y=100)
    Label(GUINuclear, text='The turbine turns a magnet,inducing an electrical current in cable around it\nwhich is then distributed by the national grid.').place(x=0, y=120)
    Label(GUINuclear, text='--------------------------------------------------------------------------------------', fg='red').place(x=0, y=155)
    #Adv/DisAdv
        #Table
    Label(GUINuclear, text='Advantages Vs Disadvantages', fg='red', font=16).place(x=0, y=175)
    Label(GUINuclear, text='Advantages', fg='red', font=14).place(x=0, y=200)
    Label(GUINuclear, text='Disadvantages', fg='red', font=14).place(x=300, y=200)
    Label(GUINuclear, text='--------------------------------------------------------------------------------------', fg='red').place(x=0, y=225)
    Label(GUINuclear, text='|---|', fg='red').place(x=200, y=200)
    Label(GUINuclear, text='|---|', fg='red').place(x=200, y=225)
    Label(GUINuclear, text='|---|', fg='red').place(x=200, y=250)
    Label(GUINuclear, text='|---|', fg='red').place(x=200, y=275)
    Label(GUINuclear, text='|---|', fg='red').place(x=200, y=300)
    Label(GUINuclear, text='|---|', fg='red').place(x=200, y=325)
    Label(GUINuclear, text='|---|', fg='red').place(x=200, y=350)
    Label(GUINuclear, text='|---|', fg='red').place(x=200, y=375)
    Label(GUINuclear, text='|---|', fg='red').place(x=200, y=400)
    Label(GUINuclear, text='|---|', fg='red').place(x=200, y=425)
        #Adv
    Label(GUINuclear, text='Few Greenhouse Gasses', font=10).place(x=0, y=245)
    Label(GUINuclear, text='-Negligible greenhouse gasses made.').place(x=0, y=265)
    Label(GUINuclear, text='Efficient', font=10).place(x=0, y=285)
    Label(GUINuclear, text='-It is very efficient.').place(x=0, y=305)
    Label(GUINuclear, text='Reliable', font=10).place(x=0, y=325)
    Label(GUINuclear, text="-Doesn't rely on the weather.").place(x=0, y=345)
    Label(GUINuclear, text='Cheap', font=10).place(x=0, y=365)
    Label(GUINuclear, text='-Uranium as a fuel is low.').place(x=0, y=385)
        #DisAdv
    Label(GUINuclear, text='Radioactive Waste', font=10).place(x=230, y=245)
    Label(GUINuclear, text='-Waste produced is radioactive.').place(x=230, y=265)
    Label(GUINuclear, text='Nuclear Accidents', font=10).place(x=230, y=285)
    Label(GUINuclear, text='-Symptoms:nausea,vomiting,diarrhea.').place(x=230, y=305)
    Label(GUINuclear, text='Initial cost', font=10).place(x=230, y=325)
    Label(GUINuclear, text='-The initial cost of the plant is high.').place(x=230, y=345)
    Label(GUINuclear, text='Not abundant', font=10).place(x=230, y=365)
    Label(GUINuclear, text='-Uranium is very scarce.').place(x=230, y=385)

    Label(GUINuclear, text='Source(1):http://www.conserve-energy-future.com/Advantages_NuclearEnergy.php').place(x=0, y=450)
    Label(GUINuclear, text='Source(2):http://www.conserve-energy-future.com/Disadvantages_NuclearEnergy.php').place(x=0, y=470)
    Label(GUINuclear, text='--------------------------------------------------------------------------------------', fg='red').place(x=0, y=490)
    #End Adv Vs DiasAdv
    #Case Study
    Label(GUINuclear, text='Case Study - Berkeley', fg='red', font=10).place(x=0, y=510)
    Label(GUINuclear, text='It is located in Gloucestershire, South West England.').place(x=0, y=530)
    Label(GUINuclear, text='It was commissioned in 1962 and decommissioned in 1989.').place(x=0, y=530)
    Label(GUINuclear, text='It has two reactors producing 276MW in total.').place(x=0, y=550)
    Label(GUINuclear, text='All fuel was removed from the site in 1992.').place(x=0, y=570)
    Label(GUINuclear, text='The turbine hall was demolished in 1995 and cooling pond in 2002.').place(x=0, y=590)
    Label(GUINuclear, text='In March 2012,5 of the 310-tonne boilers were sent to Sweden for recycling.').place(x=0, y=610)
    Label(GUINuclear, text='Source: http://en.wikipedia.org/wiki/Berkeley_nuclear_power_station').place(x=0, y=630)
    GUINuclear.mainloop()


def wind():
    GUIWind = Tk()
    GUIWind.title('Physics Project - Wind')
    GUIWind.geometry('460x600')
    #How It Works
    Label(GUIWind, text='How does it work?', fg='red', font=16).place(x=0, y=0)
    Label(GUIWind, text='The wind catches the blades on the structure.').place(x=0, y=20)
    Label(GUIWind, text='The blades are connected to a magnet,which turns.').place(x=0, y=40)
    Label(GUIWind, text='This induces an electrical current in the copper cable that surrounds the magnet.').place(x=0, y=60)
    Label(GUIWind, text='The electricity is then distributed by the national grid.').place(x=0, y=80)
    Label(GUIWind, text='--------------------------------------------------------------------------------------', fg='red').place(x=0, y=140)
    #Adv/DisAdv
        #Table
    Label(GUIWind, text='Advantages Vs Disadvantages', fg='red', font=16).place(x=0, y=160)
    Label(GUIWind, text='Advantages', fg='red', font=14).place(x=0, y=200)
    Label(GUIWind, text='Disadvantages', fg='red', font=14).place(x=300, y=200)
    Label(GUIWind, text='--------------------------------------------------------------------------------------', fg='red').place(x=0, y=225)
    Label(GUIWind, text='|---|', fg='red').place(x=200, y=200)
    Label(GUIWind, text='|---|', fg='red').place(x=200, y=225)
    Label(GUIWind, text='|---|', fg='red').place(x=200, y=250)
    Label(GUIWind, text='|---|', fg='red').place(x=200, y=275)
    Label(GUIWind, text='|---|', fg='red').place(x=200, y=300)
    Label(GUIWind, text='|---|', fg='red').place(x=200, y=325)
    Label(GUIWind, text='|---|', fg='red').place(x=200, y=350)
        #Adv
    Label(GUIWind, text='No Greenhouse Gasses', font=10).place(x=0, y=245)
    Label(GUIWind, text='-No greenhouse gasses are emitted.').place(x=0, y=265)
    Label(GUIWind, text='Space', font=10).place(x=0, y=285)
    Label(GUIWind, text='-Take up less space than coal/oil.').place(x=0, y=305)
    Label(GUIWind, text='Versatile', font=10).place(x=0, y=325)
    Label(GUIWind, text='-Can be used in a range of locations.').place(x=0, y=345)
        #DisAdv
    Label(GUIWind, text='Unreliable', font=10).place(x=230, y=245)
    Label(GUIWind, text='-The wind always blowing.').place(x=230, y=265)
    Label(GUIWind, text='Ineffective', font=10).place(x=230, y=285)
    Label(GUIWind, text='-They produce little compared to coal.').place(x=230, y=305)
    Label(GUIWind, text='Expensive', font=10).place(x=230, y=325)
    Label(GUIWind, text='-They are expensive to build.').place(x=230, y=345)


    Label(GUIWind, text='Source: http://www.clean-energy-ideas.com/wind/\nwind-energy/advantages-and-disadvantages-of-wind-energy').place(x=0, y=370)
    Label(GUIWind, text='--------------------------------------------------------------------------------------', fg='red').place(x=0, y=410)
    #End Adv Vs DiasAdv
    #Case Study
    Label(GUIWind, text='Case Study - Barrow', fg='red', font=10).place(x=0, y=430)
    Label(GUIWind, text='It is located 7km offshore in the East Irish Sea.').place(x=0, y=450)
    Label(GUIWind, text='It was commissioned in 2006 and produces 90MW.').place(x=0, y=470)
    Label(GUIWind, text='The turbines have 50m long blades(radius).').place(x=0, y=490)
    Label(GUIWind, text='The turbines are spaced 500m apart(in the row).').place(x=0, y=510)
    Label(GUIWind, text='Each row is spaced 750m apart.').place(x=0, y=530)
    Label(GUIWind, text='There are 30 turbines in total.').place(x=0, y=550)
    Label(GUIWind, text='Source: http://en.wikipedia.org/wiki/Barrow_Offshore_Wind_Farm').place(x=0, y=570)
    GUIWind.mainloop()


def wave():
    GUIWave = Tk()
    GUIWave.title('Physics Project - Wave')
    GUIWave.geometry('460x600')
    #How It Works
    Label(GUIWave, text='How does it work?', fg='red', font=16).place(x=0, y=0)
    Label(GUIWave, text='Waves make water rise and lower in a chamber.').place(x=0, y=20)
    Label(GUIWave, text='As the wave rises,the air compresses.').place(x=0, y=40)
    Label(GUIWave, text='A hole is put in the side of the wall and a turbine is installed.').place(x=0, y=60)
    Label(GUIWave, text='The compressed air is put through the turbine and it turns it.').place(x=0, y=80)
    Label(GUIWave, text='This induces an electrical current in the copper cable that surrounds the magnet.').place(x=0, y=100)
    Label(GUIWave, text='The electricity is then distributed by the national grid.').place(x=0, y=120)
    Label(GUIWave, text='--------------------------------------------------------------------------------------', fg='red').place(x=0, y=140)
    #Adv/DisAdv
        #Table
    Label(GUIWave, text='Advantages Vs Disadvantages', fg='red', font=16).place(x=0, y=160)
    Label(GUIWave, text='Advantages', fg='red', font=14).place(x=0, y=200)
    Label(GUIWave, text='Disadvantages', fg='red', font=14).place(x=300, y=200)
    Label(GUIWave, text='--------------------------------------------------------------------------------------', fg='red').place(x=0, y=225)
    Label(GUIWave, text='|---|', fg='red').place(x=200, y=200)
    Label(GUIWave, text='|---|', fg='red').place(x=200, y=225)
    Label(GUIWave, text='|---|', fg='red').place(x=200, y=250)
    Label(GUIWave, text='|---|', fg='red').place(x=200, y=275)
    Label(GUIWave, text='|---|', fg='red').place(x=200, y=300)
    Label(GUIWave, text='|---|', fg='red').place(x=200, y=325)
    Label(GUIWave, text='|---|', fg='red').place(x=200, y=350)
    Label(GUIWave, text='|---|', fg='red').place(x=200, y=375)
    Label(GUIWave, text='|---|', fg='red').place(x=200, y=400)
    Label(GUIWave, text='|---|', fg='red').place(x=200, y=425)
        #Adv
    Label(GUIWave, text='', font=10).place(x=0, y=245)
    Label(GUIWave, text='-').place(x=0, y=265)
    Label(GUIWave, text='', font=10).place(x=0, y=285)
    Label(GUIWave, text='-').place(x=0, y=305)
    Label(GUIWave, text='', font=10).place(x=0, y=325)
    Label(GUIWave, text='-').place(x=0, y=345)
    Label(GUIWave, text='', font=10).place(x=0, y=365)
    Label(GUIWave, text='-').place(x=0, y=385)
    Label(GUIWave, text='', font=10).place(x=0, y=405)
    Label(GUIWave, text='-').place(x=0, y=425)
        #DisAdv
    Label(GUIWave, text='', font=10).place(x=230, y=245)
    Label(GUIWave, text='-').place(x=230, y=265)
    Label(GUIWave, text='', font=10).place(x=230, y=285)
    Label(GUIWave, text='-').place(x=230, y=305)
    Label(GUIWave, text='', font=10).place(x=230, y=325)
    Label(GUIWave, text='-').place(x=230, y=345)
    Label(GUIWave, text='', font=10).place(x=230, y=365)
    Label(GUIWave, text='-').place(x=230, y=385)

    Label(GUIWave, text='Source: ').place(x=0, y=450)
    Label(GUIWave, text='--------------------------------------------------------------------------------------', fg='red').place(x=0, y=490)
    #End Adv Vs DiasAdv
    #Case Study
    Label(GUIWave, text='Case Study - ', fg='red', font=10).place(x=0, y=510)
    Label(GUIWave, text='').place(x=0, y=530)
    Label(GUIWave, text='').place(x=0, y=530)
    Label(GUIWave, text='').place(x=0, y=550)
    Label(GUIWave, text='').place(x=0, y=570)
    Label(GUIWave, text='').place(x=0, y=600)
    Label(GUIWave, text='').place(x=0, y=635)
    GUIWave.mainloop()


def tidal():
    GUITide = Tk()
    GUITide.title('Physics Project - Tidal')
    GUITide.geometry('460x600')
    #How It Works
    Label(GUITide, text='How does it work?', fg='red', font=16).place(x=0, y=0)
    Label(GUITide, text='').place(x=0, y=20)
    Label(GUITide, text='').place(x=0, y=40)
    Label(GUITide, text='').place(x=0, y=60)
    Label(GUITide, text='').place(x=0, y=80)
    Label(GUITide, text='').place(x=0, y=100)
    Label(GUITide, text='The electricity is then distributed by the national grid.').place(x=0, y=120)
    Label(GUITide, text='--------------------------------------------------------------------------------------', fg='red').place(x=0, y=140)
    #Adv/DisAdv
        #Table
    Label(GUITide, text='Advantages Vs Disadvantages', fg='red', font=16).place(x=0, y=160)
    Label(GUITide, text='Advantages', fg='red', font=14).place(x=0, y=200)
    Label(GUITide, text='Disadvantages', fg='red', font=14).place(x=300, y=200)
    Label(GUITide, text='--------------------------------------------------------------------------------------', fg='red').place(x=0, y=225)
    Label(GUITide, text='|---|', fg='red').place(x=200, y=200)
    Label(GUITide, text='|---|', fg='red').place(x=200, y=225)
    Label(GUITide, text='|---|', fg='red').place(x=200, y=250)
    Label(GUITide, text='|---|', fg='red').place(x=200, y=275)
    Label(GUITide, text='|---|', fg='red').place(x=200, y=300)
    Label(GUITide, text='|---|', fg='red').place(x=200, y=325)
    Label(GUITide, text='|---|', fg='red').place(x=200, y=350)
    Label(GUITide, text='|---|', fg='red').place(x=200, y=375)
    Label(GUITide, text='|---|', fg='red').place(x=200, y=400)
    Label(GUITide, text='|---|', fg='red').place(x=200, y=425)
        #Adv
    Label(GUITide, text='', font=10).place(x=0, y=245)
    Label(GUITide, text='-').place(x=0, y=265)
    Label(GUITide, text='', font=10).place(x=0, y=285)
    Label(GUITide, text='-').place(x=0, y=305)
    Label(GUITide, text='', font=10).place(x=0, y=325)
    Label(GUITide, text='-').place(x=0, y=345)
    Label(GUITide, text='', font=10).place(x=0, y=365)
    Label(GUITide, text='-').place(x=0, y=385)
    Label(GUITide, text='', font=10).place(x=0, y=405)
    Label(GUITide, text='-').place(x=0, y=425)
        #DisAdv
    Label(GUITide, text='', font=10).place(x=230, y=245)
    Label(GUITide, text='-').place(x=230, y=265)
    Label(GUITide, text='', font=10).place(x=230, y=285)
    Label(GUITide, text='-').place(x=230, y=305)
    Label(GUITide, text='', font=10).place(x=230, y=325)
    Label(GUITide, text='-').place(x=230, y=345)
    Label(GUITide, text='', font=10).place(x=230, y=365)
    Label(GUITide, text='-').place(x=230, y=385)

    Label(GUITide, text='Source: ').place(x=0, y=450)
    Label(GUITide, text='--------------------------------------------------------------------------------------', fg='red').place(x=0, y=490)
    #End Adv Vs DiasAdv
    #Case Study
    Label(GUITide, text='Case Study - ', fg='red', font=10).place(x=0, y=510)
    Label(GUITide, text='').place(x=0, y=530)
    Label(GUITide, text='').place(x=0, y=530)
    Label(GUITide, text='').place(x=0, y=550)
    Label(GUITide, text='').place(x=0, y=570)
    Label(GUITide, text='').place(x=0, y=600)
    Label(GUITide, text='').place(x=0, y=635)
    GUITide.mainloop()


def geothermal():
    GUIGeo = Tk()
    GUIGeo.title('Physics Project - Geothermal')
    GUIGeo.geometry('460x600')
    #How It Works
    Label(GUIGeo, text='How does it work?', fg='red', font=16).place(x=0, y=0)
    Label(GUIGeo, text='').place(x=0, y=20)
    Label(GUIGeo, text='').place(x=0, y=40)
    Label(GUIGeo, text='').place(x=0, y=60)
    Label(GUIGeo, text='').place(x=0, y=80)
    Label(GUIGeo, text='').place(x=0, y=100)
    Label(GUIGeo, text='The electricity is then distributed by the national grid.').place(x=0, y=120)
    Label(GUIGeo, text='--------------------------------------------------------------------------------------', fg='red').place(x=0, y=140)
    #Adv/DisAdv
        #Table
    Label(GUIGeo, text='Advantages Vs Disadvantages', fg='red', font=16).place(x=0, y=160)
    Label(GUIGeo, text='Advantages', fg='red', font=14).place(x=0, y=200)
    Label(GUIGeo, text='Disadvantages', fg='red', font=14).place(x=300, y=200)
    Label(GUIGeo, text='--------------------------------------------------------------------------------------', fg='red').place(x=0, y=225)
    Label(GUIGeo, text='|---|', fg='red').place(x=200, y=200)
    Label(GUIGeo, text='|---|', fg='red').place(x=200, y=225)
    Label(GUIGeo, text='|---|', fg='red').place(x=200, y=250)
    Label(GUIGeo, text='|---|', fg='red').place(x=200, y=275)
    Label(GUIGeo, text='|---|', fg='red').place(x=200, y=300)
    Label(GUIGeo, text='|---|', fg='red').place(x=200, y=325)
    Label(GUIGeo, text='|---|', fg='red').place(x=200, y=350)
    Label(GUIGeo, text='|---|', fg='red').place(x=200, y=375)
    Label(GUIGeo, text='|---|', fg='red').place(x=200, y=400)
    Label(GUIGeo, text='|---|', fg='red').place(x=200, y=425)
        #Adv
    Label(GUIGeo, text='', font=10).place(x=0, y=245)
    Label(GUIGeo, text='-').place(x=0, y=265)
    Label(GUIGeo, text='', font=10).place(x=0, y=285)
    Label(GUIGeo, text='-').place(x=0, y=305)
    Label(GUIGeo, text='', font=10).place(x=0, y=325)
    Label(GUIGeo, text='-').place(x=0, y=345)
    Label(GUIGeo, text='', font=10).place(x=0, y=365)
    Label(GUIGeo, text='-').place(x=0, y=385)
    Label(GUIGeo, text='', font=10).place(x=0, y=405)
    Label(GUIGeo, text='-').place(x=0, y=425)
        #DisAdv
    Label(GUIGeo, text='', font=10).place(x=230, y=245)
    Label(GUIGeo, text='-').place(x=230, y=265)
    Label(GUIGeo, text='', font=10).place(x=230, y=285)
    Label(GUIGeo, text='-').place(x=230, y=305)
    Label(GUIGeo, text='', font=10).place(x=230, y=325)
    Label(GUIGeo, text='-').place(x=230, y=345)
    Label(GUIGeo, text='', font=10).place(x=230, y=365)
    Label(GUIGeo, text='-').place(x=230, y=385)

    Label(GUIGeo, text='Source: ').place(x=0, y=450)
    Label(GUIGeo, text='--------------------------------------------------------------------------------------', fg='red').place(x=0, y=490)
    #End Adv Vs DiasAdv
    #Case Study
    Label(GUIGeo, text='Case Study - ', fg='red', font=10).place(x=0, y=510)
    Label(GUIGeo, text='').place(x=0, y=530)
    Label(GUIGeo, text='').place(x=0, y=530)
    Label(GUIGeo, text='').place(x=0, y=550)
    Label(GUIGeo, text='').place(x=0, y=570)
    Label(GUIGeo, text='').place(x=0, y=600)
    Label(GUIGeo, text='').place(x=0, y=635)
    GUIGeo.mainloop()


def hydroelectric():
    GUIHE = Tk()
    GUIHE.title('Physics Project - Hydroelectric')
    GUIHE.geometry('460x600')
    #How It Works
    Label(GUIHE, text='How does it work?', fg='red', font=16).place(x=0, y=0)
    Label(GUIHE, text='').place(x=0, y=20)
    Label(GUIHE, text='').place(x=0, y=40)
    Label(GUIHE, text='').place(x=0, y=60)
    Label(GUIHE, text='').place(x=0, y=80)
    Label(GUIHE, text='').place(x=0, y=100)
    Label(GUIHE, text='The electricity is then distributed by the national grid.').place(x=0, y=120)
    Label(GUIHE, text='--------------------------------------------------------------------------------------', fg='red').place(x=0, y=140)
    #Adv/DisAdv
        #Table
    Label(GUIHE, text='Advantages Vs Disadvantages', fg='red', font=16).place(x=0, y=160)
    Label(GUIHE, text='Advantages', fg='red', font=14).place(x=0, y=200)
    Label(GUIHE, text='Disadvantages', fg='red', font=14).place(x=300, y=200)
    Label(GUIHE, text='--------------------------------------------------------------------------------------', fg='red').place(x=0, y=225)
    Label(GUIHE, text='|---|', fg='red').place(x=200, y=200)
    Label(GUIHE, text='|---|', fg='red').place(x=200, y=225)
    Label(GUIHE, text='|---|', fg='red').place(x=200, y=250)
    Label(GUIHE, text='|---|', fg='red').place(x=200, y=275)
    Label(GUIHE, text='|---|', fg='red').place(x=200, y=300)
    Label(GUIHE, text='|---|', fg='red').place(x=200, y=325)
    Label(GUIHE, text='|---|', fg='red').place(x=200, y=350)
    Label(GUIHE, text='|---|', fg='red').place(x=200, y=375)
    Label(GUIHE, text='|---|', fg='red').place(x=200, y=400)
    Label(GUIHE, text='|---|', fg='red').place(x=200, y=425)
        #Adv
    Label(GUIHE, text='', font=10).place(x=0, y=245)
    Label(GUIHE, text='-').place(x=0, y=265)
    Label(GUIHE, text='', font=10).place(x=0, y=285)
    Label(GUIHE, text='-').place(x=0, y=305)
    Label(GUIHE, text='', font=10).place(x=0, y=325)
    Label(GUIHE, text='-').place(x=0, y=345)
    Label(GUIHE, text='', font=10).place(x=0, y=365)
    Label(GUIHE, text='-').place(x=0, y=385)
    Label(GUIHE, text='', font=10).place(x=0, y=405)
    Label(GUIHE, text='-').place(x=0, y=425)
        #DisAdv
    Label(GUIHE, text='', font=10).place(x=230, y=245)
    Label(GUIHE, text='-').place(x=230, y=265)
    Label(GUIHE, text='', font=10).place(x=230, y=285)
    Label(GUIHE, text='-').place(x=230, y=305)
    Label(GUIHE, text='', font=10).place(x=230, y=325)
    Label(GUIHE, text='-').place(x=230, y=345)
    Label(GUIHE, text='', font=10).place(x=230, y=365)
    Label(GUIHE, text='-').place(x=230, y=385)

    Label(GUIHE, text='Source: ').place(x=0, y=450)
    Label(GUIHE, text='--------------------------------------------------------------------------------------', fg='red').place(x=0, y=490)
    #End Adv Vs DiasAdv
    #Case Study
    Label(GUIHE, text='Case Study - ', fg='red', font=10).place(x=0, y=510)
    Label(GUIHE, text='').place(x=0, y=530)
    Label(GUIHE, text='').place(x=0, y=530)
    Label(GUIHE, text='').place(x=0, y=550)
    Label(GUIHE, text='').place(x=0, y=570)
    Label(GUIHE, text='').place(x=0, y=600)
    Label(GUIHE, text='').place(x=0, y=635)
    GUIHE.mainloop()

GUI = Tk()
GUI.title('Physics Project')
GUI.geometry('300x260')
Button(GUI, text='Coal Power plants', command=coal).pack()
Button(GUI, text='Oil Power plants', command=oil).pack()
Button(GUI, text='Gas Power plants', command=gas).pack()
Button(GUI, text='Biofuel Power plants', command=biofuel).pack()
Button(GUI, text='Nuclear Power plants', command=nuclear).pack()
Button(GUI, text='Wind Power plants', command=wind).pack()
Button(GUI, text='Wave Power plants', command=wave).pack()
Button(GUI, text='Tidal Power plants', command=tidal).pack()
Button(GUI, text='Geothermal Power plants', command=geothermal).pack()
Button(GUI, text='Hydroelectric Power plants', command=hydroelectric).pack()
GUI.mainloop()