__author__ = 'dugging'
from tkinter import *


def coal():
    GUICoal = Tk()
    GUICoal.title('Physics Project - Coal')
    GUICoal.geometry('460x600')
    #How It Works
    Label(GUICoal, text='How does it work?', fg='red', font=16).place(x=0, y=0)
    Label(GUICoal, text='Coal is burnt in a boiler and heats water in a vat above it.').place(x=0, y=20)
    Label(GUICoal, text='When the water evaporates, it is compressed.').place(x=0, y=40)
    Label(GUICoal, text='It is then put through a turbine which turns a magnet.').place(x=0, y=60)
    Label(GUICoal, text='This induces an electrical current in the copper cable that surrounds the magnet.').place(x=0, y=80)
    Label(GUICoal, text='Coal is burnt in a boiler and heats water in a vat above it.').place(x=0, y=100)
    Label(GUICoal, text='The electricity is then distributed by the national grid.').place(x=0, y=120)
    Label(GUICoal, text='--------------------------------------------------------------------------------------', fg='red').place(x=0, y=140)
    #Adv/DisAdv
        #Table
    Label(GUICoal, text='Advantages Vs Disadvantages', fg='red', font=16).place(x=0, y=160)
    Label(GUICoal, text='Advantages', fg='red', font=14).place(x=0, y=200)
    Label(GUICoal, text='Disadvantages', fg='red', font=14).place(x=300, y=200)
    Label(GUICoal, text='--------------------------------------------------------------------------------------', fg='red').place(x=0, y=225)
    Label(GUICoal, text='|---|', fg='red').place(x=200, y=200)
    Label(GUICoal, text='|---|', fg='red').place(x=200, y=225)
    Label(GUICoal, text='|---|', fg='red').place(x=200, y=250)
    Label(GUICoal, text='|---|', fg='red').place(x=200, y=275)
    Label(GUICoal, text='|---|', fg='red').place(x=200, y=300)
    Label(GUICoal, text='|---|', fg='red').place(x=200, y=325)
    Label(GUICoal, text='|---|', fg='red').place(x=200, y=350)
    Label(GUICoal, text='|---|', fg='red').place(x=200, y=375)
    Label(GUICoal, text='|---|', fg='red').place(x=200, y=400)
    Label(GUICoal, text='|---|', fg='red').place(x=200, y=425)
        #Adv
    Label(GUICoal, text='Reliability', font=10).place(x=0, y=245)
    Label(GUICoal, text='-They are reliable for peak times.').place(x=0, y=265)
    Label(GUICoal, text='Affordability', font=10).place(x=0, y=285)
    Label(GUICoal, text='-They are cheap.').place(x=0, y=305)
    Label(GUICoal, text='Abundance', font=10).place(x=0, y=325)
    Label(GUICoal, text='-There are over 300 years of coal left.').place(x=0, y=345)
    Label(GUICoal, text='Known technologies', font=10).place(x=0, y=365)
    Label(GUICoal, text='-We know how it works.').place(x=0, y=385)
    Label(GUICoal, text='Safety', font=10).place(x=0, y=405)
    Label(GUICoal, text='-They are generally safe.').place(x=0, y=425)
        #DisAdv
    Label(GUICoal, text='Greenhouse gas emissions', font=10).place(x=230, y=245)
    Label(GUICoal, text='-They emit Green house gas.').place(x=230, y=265)
    Label(GUICoal, text='Mining destruction', font=10).place(x=230, y=285)
    Label(GUICoal, text='-Mining coal destroys land.').place(x=230, y=305)
    Label(GUICoal, text='Generation  of waste', font=10).place(x=230, y=325)
    Label(GUICoal, text='-They produce tons of unusable waste.').place(x=230, y=345)
    Label(GUICoal, text='Emission of harmful substances', font=10).place(x=230, y=365)
    Label(GUICoal, text='-Substance like mercury\nand sulphur dioxide are released\nwhich cause harm to the\nenvironment people included.').place(x=230, y=385)

    Label(GUICoal, text='Source: http://www.brighthubengineering.com/power-plants/\n115683-advantages-and-disadvantages-of-coal-for-power-plants/').place(x=0, y=450)
    Label(GUICoal, text='--------------------------------------------------------------------------------------', fg='red').place(x=0, y=490)
    #End Adv Vs DiasAdv
    #Case Study
    Label(GUICoal, text='Case Study - Aberthaw', fg='red', font=10).place(x=0, y=510)
    Label(GUICoal, text='Aberthaw is in Barry, Vale of Glamorgan(south wales).').place(x=0, y=530)
    Label(GUICoal, text='It opened in 1966 and has three operational units.').place(x=0, y=530)
    Label(GUICoal, text='It burns 5000-6000 tonnes of coal per day contributing 6-7 GWHrs per year.').place(x=0, y=550)
    Label(GUICoal, text='In response to the renewable energy act in April\n2002 the station uses biofuel as a secondary fuel.').place(x=0, y=570)
    Label(GUICoal, text='In June 2005, station owners npower,agreed to install\nnew Flue Gas Desulfurization(FGD) equipment.').place(x=0, y=600)
    Label(GUICoal, text='The FGD equipment is planned to be installed by 2008,\nreducing sulphur dioxide levels by 90%.').place(x=0, y=635)
    GUICoal.mainloop()


def oil():
    GUIOil = Tk()
    GUIOil.title('Physics Project - Coal')
    GUIOil.geometry('460x600')
    #How It Works
    Label(GUIOil, text='How does it work?', fg='red', font=16).place(x=0, y=0)
    Label(GUIOil, text='Oil is burnt in a boiler and heats water in a vat above it.').place(x=0, y=20)
    Label(GUIOil, text='When the water evaporates, it is compressed.').place(x=0, y=40)
    Label(GUIOil, text='It is then put through a turbine which turns a magnet.').place(x=0, y=60)
    Label(GUIOil, text='This induces an electrical current in the copper cable that surrounds the magnet.').place(x=0, y=80)
    Label(GUIOil, text='Coal is burnt in a boiler and heats water in a vat above it.').place(x=0, y=100)
    Label(GUIOil, text='The electricity is then distributed by the national grid.').place(x=0, y=120)
    Label(GUIOil, text='--------------------------------------------------------------------------------------', fg='red').place(x=0, y=140)
    #Adv/DisAdv
        #Table
    Label(GUIOil, text='Advantages Vs Disadvantages', fg='red', font=16).place(x=0, y=160)
    Label(GUIOil, text='Advantages', fg='red', font=14).place(x=0, y=200)
    Label(GUIOil, text='Disadvantages', fg='red', font=14).place(x=300, y=200)
    Label(GUIOil, text='--------------------------------------------------------------------------------------', fg='red').place(x=0, y=225)
    Label(GUIOil, text='|---|', fg='red').place(x=200, y=200)
    Label(GUIOil, text='|---|', fg='red').place(x=200, y=225)
    Label(GUIOil, text='|---|', fg='red').place(x=200, y=250)
    Label(GUIOil, text='|---|', fg='red').place(x=200, y=275)
    Label(GUIOil, text='|---|', fg='red').place(x=200, y=300)
    Label(GUIOil, text='|---|', fg='red').place(x=200, y=325)
    Label(GUIOil, text='|---|', fg='red').place(x=200, y=350)
    Label(GUIOil, text='|---|', fg='red').place(x=200, y=375)
    Label(GUIOil, text='|---|', fg='red').place(x=200, y=400)
    Label(GUIOil, text='|---|', fg='red').place(x=200, y=425)
        #Adv
    Label(GUIOil, text='', font=10).place(x=0, y=245)
    Label(GUIOil, text='-').place(x=0, y=265)
    Label(GUIOil, text='', font=10).place(x=0, y=285)
    Label(GUIOil, text='-').place(x=0, y=305)
    Label(GUIOil, text='', font=10).place(x=0, y=325)
    Label(GUIOil, text='-').place(x=0, y=345)
    Label(GUIOil, text='', font=10).place(x=0, y=365)
    Label(GUIOil, text='-').place(x=0, y=385)
    Label(GUIOil, text='', font=10).place(x=0, y=405)
    Label(GUIOil, text='-').place(x=0, y=425)
        #DisAdv
    Label(GUIOil, text='', font=10).place(x=230, y=245)
    Label(GUIOil, text='-').place(x=230, y=265)
    Label(GUIOil, text='', font=10).place(x=230, y=285)
    Label(GUIOil, text='-').place(x=230, y=305)
    Label(GUIOil, text='', font=10).place(x=230, y=325)
    Label(GUIOil, text='-').place(x=230, y=345)
    Label(GUIOil, text='', font=10).place(x=230, y=365)
    Label(GUIOil, text='-').place(x=230, y=385)

    Label(GUIOil, text='Source: ').place(x=0, y=450)
    Label(GUIOil, text='--------------------------------------------------------------------------------------', fg='red').place(x=0, y=490)
    #End Adv Vs DiasAdv
    #Case Study
    Label(GUIOil, text='Case Study - ', fg='red', font=10).place(x=0, y=510)
    Label(GUIOil, text='').place(x=0, y=530)
    Label(GUIOil, text='').place(x=0, y=530)
    Label(GUIOil, text='').place(x=0, y=550)
    Label(GUIOil, text='').place(x=0, y=570)
    Label(GUIOil, text='').place(x=0, y=600)
    Label(GUIOil, text='').place(x=0, y=635)
    GUIOil.mainloop()


def gas():
    GUIGas = Tk()
    GUIGas.title('Physics Project - Coal')
    GUIGas.geometry('460x600')
    #How It Works
    Label(GUIGas, text='How does it work?', fg='red', font=16).place(x=0, y=0)
    Label(GUIGas, text='Oil is burnt in a boiler and heats water in a vat above it.').place(x=0, y=20)
    Label(GUIGas, text='When the water evaporates, it is compressed.').place(x=0, y=40)
    Label(GUIGas, text='It is then put through a turbine which turns a magnet.').place(x=0, y=60)
    Label(GUIGas, text='This induces an electrical current in the copper cable that surrounds the magnet.').place(x=0, y=80)
    Label(GUIGas, text='Coal is burnt in a boiler and heats water in a vat above it.').place(x=0, y=100)
    Label(GUIGas, text='The electricity is then distributed by the national grid.').place(x=0, y=120)
    Label(GUIGas, text='--------------------------------------------------------------------------------------', fg='red').place(x=0, y=140)
    #Adv/DisAdv
        #Table
    Label(GUIGas, text='Advantages Vs Disadvantages', fg='red', font=16).place(x=0, y=160)
    Label(GUIGas, text='Advantages', fg='red', font=14).place(x=0, y=200)
    Label(GUIGas, text='Disadvantages', fg='red', font=14).place(x=300, y=200)
    Label(GUIGas, text='--------------------------------------------------------------------------------------', fg='red').place(x=0, y=225)
    Label(GUIGas, text='|---|', fg='red').place(x=200, y=200)
    Label(GUIGas, text='|---|', fg='red').place(x=200, y=225)
    Label(GUIGas, text='|---|', fg='red').place(x=200, y=250)
    Label(GUIGas, text='|---|', fg='red').place(x=200, y=275)
    Label(GUIGas, text='|---|', fg='red').place(x=200, y=300)
    Label(GUIGas, text='|---|', fg='red').place(x=200, y=325)
    Label(GUIGas, text='|---|', fg='red').place(x=200, y=350)
    Label(GUIGas, text='|---|', fg='red').place(x=200, y=375)
    Label(GUIGas, text='|---|', fg='red').place(x=200, y=400)
    Label(GUIGas, text='|---|', fg='red').place(x=200, y=425)
        #Adv
    Label(GUIGas, text='', font=10).place(x=0, y=245)
    Label(GUIGas, text='-').place(x=0, y=265)
    Label(GUIGas, text='', font=10).place(x=0, y=285)
    Label(GUIGas, text='-').place(x=0, y=305)
    Label(GUIGas, text='', font=10).place(x=0, y=325)
    Label(GUIGas, text='-').place(x=0, y=345)
    Label(GUIGas, text='', font=10).place(x=0, y=365)
    Label(GUIGas, text='-').place(x=0, y=385)
    Label(GUIGas, text='', font=10).place(x=0, y=405)
    Label(GUIGas, text='-').place(x=0, y=425)
        #DisAdv
    Label(GUIGas, text='', font=10).place(x=230, y=245)
    Label(GUIGas, text='-').place(x=230, y=265)
    Label(GUIGas, text='', font=10).place(x=230, y=285)
    Label(GUIGas, text='-').place(x=230, y=305)
    Label(GUIGas, text='', font=10).place(x=230, y=325)
    Label(GUIGas, text='-').place(x=230, y=345)
    Label(GUIGas, text='', font=10).place(x=230, y=365)
    Label(GUIGas, text='-').place(x=230, y=385)

    Label(GUIGas, text='Source: ').place(x=0, y=450)
    Label(GUIGas, text='--------------------------------------------------------------------------------------', fg='red').place(x=0, y=490)
    #End Adv Vs DiasAdv
    #Case Study
    Label(GUIGas, text='Case Study - ', fg='red', font=10).place(x=0, y=510)
    Label(GUIGas, text='').place(x=0, y=530)
    Label(GUIGas, text='').place(x=0, y=530)
    Label(GUIGas, text='').place(x=0, y=550)
    Label(GUIGas, text='').place(x=0, y=570)
    Label(GUIGas, text='').place(x=0, y=600)
    Label(GUIGas, text='').place(x=0, y=635)
    GUIGas.mainloop()


def biofuel():
    GUIBio = Tk()
    GUIBio.title('Physics Project - Coal')
    GUIBio.geometry('460x600')
    #How It Works
    Label(GUIBio, text='How does it work?', fg='red', font=16).place(x=0, y=0)
    Label(GUIBio, text='Oil is burnt in a boiler and heats water in a vat above it.').place(x=0, y=20)
    Label(GUIBio, text='When the water evaporates, it is compressed.').place(x=0, y=40)
    Label(GUIBio, text='It is then put through a turbine which turns a magnet.').place(x=0, y=60)
    Label(GUIBio, text='This induces an electrical current in the copper cable that surrounds the magnet.').place(x=0, y=80)
    Label(GUIBio, text='Coal is burnt in a boiler and heats water in a vat above it.').place(x=0, y=100)
    Label(GUIBio, text='The electricity is then distributed by the national grid.').place(x=0, y=120)
    Label(GUIBio, text='--------------------------------------------------------------------------------------', fg='red').place(x=0, y=140)
    #Adv/DisAdv
        #Table
    Label(GUIBio, text='Advantages Vs Disadvantages', fg='red', font=16).place(x=0, y=160)
    Label(GUIBio, text='Advantages', fg='red', font=14).place(x=0, y=200)
    Label(GUIBio, text='Disadvantages', fg='red', font=14).place(x=300, y=200)
    Label(GUIBio, text='--------------------------------------------------------------------------------------', fg='red').place(x=0, y=225)
    Label(GUIBio, text='|---|', fg='red').place(x=200, y=200)
    Label(GUIBio, text='|---|', fg='red').place(x=200, y=225)
    Label(GUIBio, text='|---|', fg='red').place(x=200, y=250)
    Label(GUIBio, text='|---|', fg='red').place(x=200, y=275)
    Label(GUIBio, text='|---|', fg='red').place(x=200, y=300)
    Label(GUIBio, text='|---|', fg='red').place(x=200, y=325)
    Label(GUIBio, text='|---|', fg='red').place(x=200, y=350)
    Label(GUIBio, text='|---|', fg='red').place(x=200, y=375)
    Label(GUIBio, text='|---|', fg='red').place(x=200, y=400)
    Label(GUIBio, text='|---|', fg='red').place(x=200, y=425)
        #Adv
    Label(GUIBio, text='', font=10).place(x=0, y=245)
    Label(GUIBio, text='-').place(x=0, y=265)
    Label(GUIBio, text='', font=10).place(x=0, y=285)
    Label(GUIBio, text='-').place(x=0, y=305)
    Label(GUIBio, text='', font=10).place(x=0, y=325)
    Label(GUIBio, text='-').place(x=0, y=345)
    Label(GUIBio, text='', font=10).place(x=0, y=365)
    Label(GUIBio, text='-').place(x=0, y=385)
    Label(GUIBio, text='', font=10).place(x=0, y=405)
    Label(GUIBio, text='-').place(x=0, y=425)
        #DisAdv
    Label(GUIBio, text='', font=10).place(x=230, y=245)
    Label(GUIBio, text='-').place(x=230, y=265)
    Label(GUIBio, text='', font=10).place(x=230, y=285)
    Label(GUIBio, text='-').place(x=230, y=305)
    Label(GUIBio, text='', font=10).place(x=230, y=325)
    Label(GUIBio, text='-').place(x=230, y=345)
    Label(GUIBio, text='', font=10).place(x=230, y=365)
    Label(GUIBio, text='-').place(x=230, y=385)

    Label(GUIBio, text='Source: ').place(x=0, y=450)
    Label(GUIBio, text='--------------------------------------------------------------------------------------', fg='red').place(x=0, y=490)
    #End Adv Vs DiasAdv
    #Case Study
    Label(GUIBio, text='Case Study - ', fg='red', font=10).place(x=0, y=510)
    Label(GUIBio, text='').place(x=0, y=530)
    Label(GUIBio, text='').place(x=0, y=530)
    Label(GUIBio, text='').place(x=0, y=550)
    Label(GUIBio, text='').place(x=0, y=570)
    Label(GUIBio, text='').place(x=0, y=600)
    Label(GUIBio, text='').place(x=0, y=635)
    GUIBio.mainloop()


def nuclear():
    GUINuclear = Tk()
    GUINuclear.title('Physics Project - Coal')
    GUINuclear.geometry('460x600')
    #How It Works
    Label(GUINuclear, text='How does it work?', fg='red', font=16).place(x=0, y=0)
    Label(GUINuclear, text='Oil is burnt in a boiler and heats water in a vat above it.').place(x=0, y=20)
    Label(GUINuclear, text='When the water evaporates, it is compressed.').place(x=0, y=40)
    Label(GUINuclear, text='It is then put through a turbine which turns a magnet.').place(x=0, y=60)
    Label(GUINuclear, text='This induces an electrical current in the copper cable that surrounds the magnet.').place(x=0, y=80)
    Label(GUINuclear, text='Coal is burnt in a boiler and heats water in a vat above it.').place(x=0, y=100)
    Label(GUINuclear, text='The electricity is then distributed by the national grid.').place(x=0, y=120)
    Label(GUINuclear, text='--------------------------------------------------------------------------------------', fg='red').place(x=0, y=140)
    #Adv/DisAdv
        #Table
    Label(GUINuclear, text='Advantages Vs Disadvantages', fg='red', font=16).place(x=0, y=160)
    Label(GUINuclear, text='Advantages', fg='red', font=14).place(x=0, y=200)
    Label(GUINuclear, text='Disadvantages', fg='red', font=14).place(x=300, y=200)
    Label(GUINuclear, text='--------------------------------------------------------------------------------------', fg='red').place(x=0, y=225)
    Label(GUINuclear, text='|---|', fg='red').place(x=200, y=200)
    Label(GUINuclear, text='|---|', fg='red').place(x=200, y=225)
    Label(GUINuclear, text='|---|', fg='red').place(x=200, y=250)
    Label(GUINuclear, text='|---|', fg='red').place(x=200, y=275)
    Label(GUINuclear, text='|---|', fg='red').place(x=200, y=300)
    Label(GUINuclear, text='|---|', fg='red').place(x=200, y=325)
    Label(GUINuclear, text='|---|', fg='red').place(x=200, y=350)
    Label(GUINuclear, text='|---|', fg='red').place(x=200, y=375)
    Label(GUINuclear, text='|---|', fg='red').place(x=200, y=400)
    Label(GUINuclear, text='|---|', fg='red').place(x=200, y=425)
        #Adv
    Label(GUINuclear, text='', font=10).place(x=0, y=245)
    Label(GUINuclear, text='-').place(x=0, y=265)
    Label(GUINuclear, text='', font=10).place(x=0, y=285)
    Label(GUINuclear, text='-').place(x=0, y=305)
    Label(GUINuclear, text='', font=10).place(x=0, y=325)
    Label(GUINuclear, text='-').place(x=0, y=345)
    Label(GUINuclear, text='', font=10).place(x=0, y=365)
    Label(GUINuclear, text='-').place(x=0, y=385)
    Label(GUINuclear, text='', font=10).place(x=0, y=405)
    Label(GUINuclear, text='-').place(x=0, y=425)
        #DisAdv
    Label(GUINuclear, text='', font=10).place(x=230, y=245)
    Label(GUINuclear, text='-').place(x=230, y=265)
    Label(GUINuclear, text='', font=10).place(x=230, y=285)
    Label(GUINuclear, text='-').place(x=230, y=305)
    Label(GUINuclear, text='', font=10).place(x=230, y=325)
    Label(GUINuclear, text='-').place(x=230, y=345)
    Label(GUINuclear, text='', font=10).place(x=230, y=365)
    Label(GUINuclear, text='-').place(x=230, y=385)

    Label(GUINuclear, text='Source: ').place(x=0, y=450)
    Label(GUINuclear, text='--------------------------------------------------------------------------------------', fg='red').place(x=0, y=490)
    #End Adv Vs DiasAdv
    #Case Study
    Label(GUINuclear, text='Case Study - ', fg='red', font=10).place(x=0, y=510)
    Label(GUINuclear, text='').place(x=0, y=530)
    Label(GUINuclear, text='').place(x=0, y=530)
    Label(GUINuclear, text='').place(x=0, y=550)
    Label(GUINuclear, text='').place(x=0, y=570)
    Label(GUINuclear, text='').place(x=0, y=600)
    Label(GUINuclear, text='').place(x=0, y=635)
    GUINuclear.mainloop()


def wind():
    GUIWind = Tk()
    GUIWind.title('Physics Project - Coal')
    GUIWind.geometry('460x600')
    #How It Works
    Label(GUIWind, text='How does it work?', fg='red', font=16).place(x=0, y=0)
    Label(GUIWind, text='Oil is burnt in a boiler and heats water in a vat above it.').place(x=0, y=20)
    Label(GUIWind, text='When the water evaporates, it is compressed.').place(x=0, y=40)
    Label(GUIWind, text='It is then put through a turbine which turns a magnet.').place(x=0, y=60)
    Label(GUIWind, text='This induces an electrical current in the copper cable that surrounds the magnet.').place(x=0, y=80)
    Label(GUIWind, text='Coal is burnt in a boiler and heats water in a vat above it.').place(x=0, y=100)
    Label(GUIWind, text='The electricity is then distributed by the national grid.').place(x=0, y=120)
    Label(GUIWind, text='--------------------------------------------------------------------------------------', fg='red').place(x=0, y=140)
    #Adv/DisAdv
        #Table
    Label(GUIWind, text='Advantages Vs Disadvantages', fg='red', font=16).place(x=0, y=160)
    Label(GUIWind, text='Advantages', fg='red', font=14).place(x=0, y=200)
    Label(GUIWind, text='Disadvantages', fg='red', font=14).place(x=300, y=200)
    Label(GUIWind, text='--------------------------------------------------------------------------------------', fg='red').place(x=0, y=225)
    Label(GUIWind, text='|---|', fg='red').place(x=200, y=200)
    Label(GUIWind, text='|---|', fg='red').place(x=200, y=225)
    Label(GUIWind, text='|---|', fg='red').place(x=200, y=250)
    Label(GUIWind, text='|---|', fg='red').place(x=200, y=275)
    Label(GUIWind, text='|---|', fg='red').place(x=200, y=300)
    Label(GUIWind, text='|---|', fg='red').place(x=200, y=325)
    Label(GUIWind, text='|---|', fg='red').place(x=200, y=350)
    Label(GUIWind, text='|---|', fg='red').place(x=200, y=375)
    Label(GUIWind, text='|---|', fg='red').place(x=200, y=400)
    Label(GUIWind, text='|---|', fg='red').place(x=200, y=425)
        #Adv
    Label(GUIWind, text='', font=10).place(x=0, y=245)
    Label(GUIWind, text='-').place(x=0, y=265)
    Label(GUIWind, text='', font=10).place(x=0, y=285)
    Label(GUIWind, text='-').place(x=0, y=305)
    Label(GUIWind, text='', font=10).place(x=0, y=325)
    Label(GUIWind, text='-').place(x=0, y=345)
    Label(GUIWind, text='', font=10).place(x=0, y=365)
    Label(GUIWind, text='-').place(x=0, y=385)
    Label(GUIWind, text='', font=10).place(x=0, y=405)
    Label(GUIWind, text='-').place(x=0, y=425)
        #DisAdv
    Label(GUIWind, text='', font=10).place(x=230, y=245)
    Label(GUIWind, text='-').place(x=230, y=265)
    Label(GUIWind, text='', font=10).place(x=230, y=285)
    Label(GUIWind, text='-').place(x=230, y=305)
    Label(GUIWind, text='', font=10).place(x=230, y=325)
    Label(GUIWind, text='-').place(x=230, y=345)
    Label(GUIWind, text='', font=10).place(x=230, y=365)
    Label(GUIWind, text='-').place(x=230, y=385)

    Label(GUIWind, text='Source: ').place(x=0, y=450)
    Label(GUIWind, text='--------------------------------------------------------------------------------------', fg='red').place(x=0, y=490)
    #End Adv Vs DiasAdv
    #Case Study
    Label(GUIWind, text='Case Study - ', fg='red', font=10).place(x=0, y=510)
    Label(GUIWind, text='').place(x=0, y=530)
    Label(GUIWind, text='').place(x=0, y=530)
    Label(GUIWind, text='').place(x=0, y=550)
    Label(GUIWind, text='').place(x=0, y=570)
    Label(GUIWind, text='').place(x=0, y=600)
    Label(GUIWind, text='').place(x=0, y=635)
    GUIWind.mainloop()


def wave():
    GUIWave = Tk()
    GUIWave.title('Physics Project - Coal')
    GUIWave.geometry('460x600')
    #How It Works
    Label(GUIWave, text='How does it work?', fg='red', font=16).place(x=0, y=0)
    Label(GUIWave, text='Oil is burnt in a boiler and heats water in a vat above it.').place(x=0, y=20)
    Label(GUIWave, text='When the water evaporates, it is compressed.').place(x=0, y=40)
    Label(GUIWave, text='It is then put through a turbine which turns a magnet.').place(x=0, y=60)
    Label(GUIWave, text='This induces an electrical current in the copper cable that surrounds the magnet.').place(x=0, y=80)
    Label(GUIWave, text='Coal is burnt in a boiler and heats water in a vat above it.').place(x=0, y=100)
    Label(GUIWave, text='The electricity is then distributed by the national grid.').place(x=0, y=120)
    Label(GUIWave, text='--------------------------------------------------------------------------------------', fg='red').place(x=0, y=140)
    #Adv/DisAdv
        #Table
    Label(GUIWave, text='Advantages Vs Disadvantages', fg='red', font=16).place(x=0, y=160)
    Label(GUIWave, text='Advantages', fg='red', font=14).place(x=0, y=200)
    Label(GUIWave, text='Disadvantages', fg='red', font=14).place(x=300, y=200)
    Label(GUIWave, text='--------------------------------------------------------------------------------------', fg='red').place(x=0, y=225)
    Label(GUIWave, text='|---|', fg='red').place(x=200, y=200)
    Label(GUIWave, text='|---|', fg='red').place(x=200, y=225)
    Label(GUIWave, text='|---|', fg='red').place(x=200, y=250)
    Label(GUIWave, text='|---|', fg='red').place(x=200, y=275)
    Label(GUIWave, text='|---|', fg='red').place(x=200, y=300)
    Label(GUIWave, text='|---|', fg='red').place(x=200, y=325)
    Label(GUIWave, text='|---|', fg='red').place(x=200, y=350)
    Label(GUIWave, text='|---|', fg='red').place(x=200, y=375)
    Label(GUIWave, text='|---|', fg='red').place(x=200, y=400)
    Label(GUIWave, text='|---|', fg='red').place(x=200, y=425)
        #Adv
    Label(GUIWave, text='', font=10).place(x=0, y=245)
    Label(GUIWave, text='-').place(x=0, y=265)
    Label(GUIWave, text='', font=10).place(x=0, y=285)
    Label(GUIWave, text='-').place(x=0, y=305)
    Label(GUIWave, text='', font=10).place(x=0, y=325)
    Label(GUIWave, text='-').place(x=0, y=345)
    Label(GUIWave, text='', font=10).place(x=0, y=365)
    Label(GUIWave, text='-').place(x=0, y=385)
    Label(GUIWave, text='', font=10).place(x=0, y=405)
    Label(GUIWave, text='-').place(x=0, y=425)
        #DisAdv
    Label(GUIWave, text='', font=10).place(x=230, y=245)
    Label(GUIWave, text='-').place(x=230, y=265)
    Label(GUIWave, text='', font=10).place(x=230, y=285)
    Label(GUIWave, text='-').place(x=230, y=305)
    Label(GUIWave, text='', font=10).place(x=230, y=325)
    Label(GUIWave, text='-').place(x=230, y=345)
    Label(GUIWave, text='', font=10).place(x=230, y=365)
    Label(GUIWave, text='-').place(x=230, y=385)

    Label(GUIWave, text='Source: ').place(x=0, y=450)
    Label(GUIWave, text='--------------------------------------------------------------------------------------', fg='red').place(x=0, y=490)
    #End Adv Vs DiasAdv
    #Case Study
    Label(GUIWave, text='Case Study - ', fg='red', font=10).place(x=0, y=510)
    Label(GUIWave, text='').place(x=0, y=530)
    Label(GUIWave, text='').place(x=0, y=530)
    Label(GUIWave, text='').place(x=0, y=550)
    Label(GUIWave, text='').place(x=0, y=570)
    Label(GUIWave, text='').place(x=0, y=600)
    Label(GUIWave, text='').place(x=0, y=635)
    GUIWave.mainloop()


def tidal():
    GUITide = Tk()
    GUITide.title('Physics Project - Coal')
    GUITide.geometry('460x600')
    #How It Works
    Label(GUITide, text='How does it work?', fg='red', font=16).place(x=0, y=0)
    Label(GUITide, text='Oil is burnt in a boiler and heats water in a vat above it.').place(x=0, y=20)
    Label(GUITide, text='When the water evaporates, it is compressed.').place(x=0, y=40)
    Label(GUITide, text='It is then put through a turbine which turns a magnet.').place(x=0, y=60)
    Label(GUITide, text='This induces an electrical current in the copper cable that surrounds the magnet.').place(x=0, y=80)
    Label(GUITide, text='Coal is burnt in a boiler and heats water in a vat above it.').place(x=0, y=100)
    Label(GUITide, text='The electricity is then distributed by the national grid.').place(x=0, y=120)
    Label(GUITide, text='--------------------------------------------------------------------------------------', fg='red').place(x=0, y=140)
    #Adv/DisAdv
        #Table
    Label(GUITide, text='Advantages Vs Disadvantages', fg='red', font=16).place(x=0, y=160)
    Label(GUITide, text='Advantages', fg='red', font=14).place(x=0, y=200)
    Label(GUITide, text='Disadvantages', fg='red', font=14).place(x=300, y=200)
    Label(GUITide, text='--------------------------------------------------------------------------------------', fg='red').place(x=0, y=225)
    Label(GUITide, text='|---|', fg='red').place(x=200, y=200)
    Label(GUITide, text='|---|', fg='red').place(x=200, y=225)
    Label(GUITide, text='|---|', fg='red').place(x=200, y=250)
    Label(GUITide, text='|---|', fg='red').place(x=200, y=275)
    Label(GUITide, text='|---|', fg='red').place(x=200, y=300)
    Label(GUITide, text='|---|', fg='red').place(x=200, y=325)
    Label(GUITide, text='|---|', fg='red').place(x=200, y=350)
    Label(GUITide, text='|---|', fg='red').place(x=200, y=375)
    Label(GUITide, text='|---|', fg='red').place(x=200, y=400)
    Label(GUITide, text='|---|', fg='red').place(x=200, y=425)
        #Adv
    Label(GUITide, text='', font=10).place(x=0, y=245)
    Label(GUITide, text='-').place(x=0, y=265)
    Label(GUITide, text='', font=10).place(x=0, y=285)
    Label(GUITide, text='-').place(x=0, y=305)
    Label(GUITide, text='', font=10).place(x=0, y=325)
    Label(GUITide, text='-').place(x=0, y=345)
    Label(GUITide, text='', font=10).place(x=0, y=365)
    Label(GUITide, text='-').place(x=0, y=385)
    Label(GUITide, text='', font=10).place(x=0, y=405)
    Label(GUITide, text='-').place(x=0, y=425)
        #DisAdv
    Label(GUITide, text='', font=10).place(x=230, y=245)
    Label(GUITide, text='-').place(x=230, y=265)
    Label(GUITide, text='', font=10).place(x=230, y=285)
    Label(GUITide, text='-').place(x=230, y=305)
    Label(GUITide, text='', font=10).place(x=230, y=325)
    Label(GUITide, text='-').place(x=230, y=345)
    Label(GUITide, text='', font=10).place(x=230, y=365)
    Label(GUITide, text='-').place(x=230, y=385)

    Label(GUITide, text='Source: ').place(x=0, y=450)
    Label(GUITide, text='--------------------------------------------------------------------------------------', fg='red').place(x=0, y=490)
    #End Adv Vs DiasAdv
    #Case Study
    Label(GUITide, text='Case Study - ', fg='red', font=10).place(x=0, y=510)
    Label(GUITide, text='').place(x=0, y=530)
    Label(GUITide, text='').place(x=0, y=530)
    Label(GUITide, text='').place(x=0, y=550)
    Label(GUITide, text='').place(x=0, y=570)
    Label(GUITide, text='').place(x=0, y=600)
    Label(GUITide, text='').place(x=0, y=635)
    GUITide.mainloop()


def geothermal():
    GUIGeo = Tk()
    GUIGeo.title('Physics Project - Coal')
    GUIGeo.geometry('460x600')
    #How It Works
    Label(GUIGeo, text='How does it work?', fg='red', font=16).place(x=0, y=0)
    Label(GUIGeo, text='Oil is burnt in a boiler and heats water in a vat above it.').place(x=0, y=20)
    Label(GUIGeo, text='When the water evaporates, it is compressed.').place(x=0, y=40)
    Label(GUIGeo, text='It is then put through a turbine which turns a magnet.').place(x=0, y=60)
    Label(GUIGeo, text='This induces an electrical current in the copper cable that surrounds the magnet.').place(x=0, y=80)
    Label(GUIGeo, text='Coal is burnt in a boiler and heats water in a vat above it.').place(x=0, y=100)
    Label(GUIGeo, text='The electricity is then distributed by the national grid.').place(x=0, y=120)
    Label(GUIGeo, text='--------------------------------------------------------------------------------------', fg='red').place(x=0, y=140)
    #Adv/DisAdv
        #Table
    Label(GUIGeo, text='Advantages Vs Disadvantages', fg='red', font=16).place(x=0, y=160)
    Label(GUIGeo, text='Advantages', fg='red', font=14).place(x=0, y=200)
    Label(GUIGeo, text='Disadvantages', fg='red', font=14).place(x=300, y=200)
    Label(GUIGeo, text='--------------------------------------------------------------------------------------', fg='red').place(x=0, y=225)
    Label(GUIGeo, text='|---|', fg='red').place(x=200, y=200)
    Label(GUIGeo, text='|---|', fg='red').place(x=200, y=225)
    Label(GUIGeo, text='|---|', fg='red').place(x=200, y=250)
    Label(GUIGeo, text='|---|', fg='red').place(x=200, y=275)
    Label(GUIGeo, text='|---|', fg='red').place(x=200, y=300)
    Label(GUIGeo, text='|---|', fg='red').place(x=200, y=325)
    Label(GUIGeo, text='|---|', fg='red').place(x=200, y=350)
    Label(GUIGeo, text='|---|', fg='red').place(x=200, y=375)
    Label(GUIGeo, text='|---|', fg='red').place(x=200, y=400)
    Label(GUIGeo, text='|---|', fg='red').place(x=200, y=425)
        #Adv
    Label(GUIGeo, text='', font=10).place(x=0, y=245)
    Label(GUIGeo, text='-').place(x=0, y=265)
    Label(GUIGeo, text='', font=10).place(x=0, y=285)
    Label(GUIGeo, text='-').place(x=0, y=305)
    Label(GUIGeo, text='', font=10).place(x=0, y=325)
    Label(GUIGeo, text='-').place(x=0, y=345)
    Label(GUIGeo, text='', font=10).place(x=0, y=365)
    Label(GUIGeo, text='-').place(x=0, y=385)
    Label(GUIGeo, text='', font=10).place(x=0, y=405)
    Label(GUIGeo, text='-').place(x=0, y=425)
        #DisAdv
    Label(GUIGeo, text='', font=10).place(x=230, y=245)
    Label(GUIGeo, text='-').place(x=230, y=265)
    Label(GUIGeo, text='', font=10).place(x=230, y=285)
    Label(GUIGeo, text='-').place(x=230, y=305)
    Label(GUIGeo, text='', font=10).place(x=230, y=325)
    Label(GUIGeo, text='-').place(x=230, y=345)
    Label(GUIGeo, text='', font=10).place(x=230, y=365)
    Label(GUIGeo, text='-').place(x=230, y=385)

    Label(GUIGeo, text='Source: ').place(x=0, y=450)
    Label(GUIGeo, text='--------------------------------------------------------------------------------------', fg='red').place(x=0, y=490)
    #End Adv Vs DiasAdv
    #Case Study
    Label(GUIGeo, text='Case Study - ', fg='red', font=10).place(x=0, y=510)
    Label(GUIGeo, text='').place(x=0, y=530)
    Label(GUIGeo, text='').place(x=0, y=530)
    Label(GUIGeo, text='').place(x=0, y=550)
    Label(GUIGeo, text='').place(x=0, y=570)
    Label(GUIGeo, text='').place(x=0, y=600)
    Label(GUIGeo, text='').place(x=0, y=635)
    GUIGeo.mainloop()


def hydroelectric():
    GUIHE = Tk()
    GUIHE.title('Physics Project - Coal')
    GUIHE.geometry('460x600')
    #How It Works
    Label(GUIHE, text='How does it work?', fg='red', font=16).place(x=0, y=0)
    Label(GUIHE, text='Oil is burnt in a boiler and heats water in a vat above it.').place(x=0, y=20)
    Label(GUIHE, text='When the water evaporates, it is compressed.').place(x=0, y=40)
    Label(GUIHE, text='It is then put through a turbine which turns a magnet.').place(x=0, y=60)
    Label(GUIHE, text='This induces an electrical current in the copper cable that surrounds the magnet.').place(x=0, y=80)
    Label(GUIHE, text='Coal is burnt in a boiler and heats water in a vat above it.').place(x=0, y=100)
    Label(GUIHE, text='The electricity is then distributed by the national grid.').place(x=0, y=120)
    Label(GUIHE, text='--------------------------------------------------------------------------------------', fg='red').place(x=0, y=140)
    #Adv/DisAdv
        #Table
    Label(GUIHE, text='Advantages Vs Disadvantages', fg='red', font=16).place(x=0, y=160)
    Label(GUIHE, text='Advantages', fg='red', font=14).place(x=0, y=200)
    Label(GUIHE, text='Disadvantages', fg='red', font=14).place(x=300, y=200)
    Label(GUIHE, text='--------------------------------------------------------------------------------------', fg='red').place(x=0, y=225)
    Label(GUIHE, text='|---|', fg='red').place(x=200, y=200)
    Label(GUIHE, text='|---|', fg='red').place(x=200, y=225)
    Label(GUIHE, text='|---|', fg='red').place(x=200, y=250)
    Label(GUIHE, text='|---|', fg='red').place(x=200, y=275)
    Label(GUIHE, text='|---|', fg='red').place(x=200, y=300)
    Label(GUIHE, text='|---|', fg='red').place(x=200, y=325)
    Label(GUIHE, text='|---|', fg='red').place(x=200, y=350)
    Label(GUIHE, text='|---|', fg='red').place(x=200, y=375)
    Label(GUIHE, text='|---|', fg='red').place(x=200, y=400)
    Label(GUIHE, text='|---|', fg='red').place(x=200, y=425)
        #Adv
    Label(GUIHE, text='', font=10).place(x=0, y=245)
    Label(GUIHE, text='-').place(x=0, y=265)
    Label(GUIHE, text='', font=10).place(x=0, y=285)
    Label(GUIHE, text='-').place(x=0, y=305)
    Label(GUIHE, text='', font=10).place(x=0, y=325)
    Label(GUIHE, text='-').place(x=0, y=345)
    Label(GUIHE, text='', font=10).place(x=0, y=365)
    Label(GUIHE, text='-').place(x=0, y=385)
    Label(GUIHE, text='', font=10).place(x=0, y=405)
    Label(GUIHE, text='-').place(x=0, y=425)
        #DisAdv
    Label(GUIHE, text='', font=10).place(x=230, y=245)
    Label(GUIHE, text='-').place(x=230, y=265)
    Label(GUIHE, text='', font=10).place(x=230, y=285)
    Label(GUIHE, text='-').place(x=230, y=305)
    Label(GUIHE, text='', font=10).place(x=230, y=325)
    Label(GUIHE, text='-').place(x=230, y=345)
    Label(GUIHE, text='', font=10).place(x=230, y=365)
    Label(GUIHE, text='-').place(x=230, y=385)

    Label(GUIHE, text='Source: ').place(x=0, y=450)
    Label(GUIHE, text='--------------------------------------------------------------------------------------', fg='red').place(x=0, y=490)
    #End Adv Vs DiasAdv
    #Case Study
    Label(GUIHE, text='Case Study - ', fg='red', font=10).place(x=0, y=510)
    Label(GUIHE, text='').place(x=0, y=530)
    Label(GUIHE, text='').place(x=0, y=530)
    Label(GUIHE, text='').place(x=0, y=550)
    Label(GUIHE, text='').place(x=0, y=570)
    Label(GUIHE, text='').place(x=0, y=600)
    Label(GUIHE, text='').place(x=0, y=635)
    GUIHE.mainloop()

coal()

# GUI = Tk()
# GUI.title('Physics Project')
# GUI.geometry('300x260')
# Button(GUI, text='Coal Power plants', command=coal).pack()
# Button(GUI, text='Oil Power plants', command=oil).pack()
# Button(GUI, text='Gas Power plants', command=gas).pack()
# Button(GUI, text='Biofuel Power plants', command=coal).pack()
# Button(GUI, text='Nuclear Power plants', command=oil).pack()
# Button(GUI, text='Wind Power plants', command=gas).pack()
# Button(GUI, text='Wave Power plants', command=coal).pack()
# Button(GUI, text='Tidal Power plants', command=oil).pack()
# Button(GUI, text='Geothermal Power plants', command=gas).pack()
# Button(GUI, text='Hydroelectric Power plants', command=gas).pack()
# GUI.mainloop()